### ISSUE TITLE
Sub-circuit termination

### ISSUE THREAD

**Issue by quantumkoen** [QE-Lab/libqasm#3]
A suggestion for a future version of QASM (from our front-end team):

When you define a sub circuit it can only be terminated by defining a new sub circuit. This is a strange restriction. A more obvious choice would be to 1) indent the commands that are part of the subcircuit or 2) to use accolades {…} to define the sub circuit.

**Comment by kel85uk** [comment]
It's a suggestion, which can be closed since the design choice of cQASM 1.0 is now fixed.
