### ISSUE TITLE
Better error handling in Semantic checker

### ISSUE THREAD

**Issue by kel85uk** [QE-Lab/libqasm#40]
The semantic checker is far from complete. We need to make sure the semantic checker does:

* Check that operations are having correct vector lengths.
* Check that keywords are not used as maps.
* Provide clearer exception messages for the user.

**Comment by jvanstraten** [comment]
> Check that operations are having correct vector lengths.

This is implemented in the new semantic analyzer added in #105.

> Check that keywords are not used as maps.

This was lexically impossible to do before #105, and explicitly requested as feature in #56. It's now explicitly legal in the sense that there are way fewer keywords (only `qubits`, `map`, `var`, and `cond`).

> Provide clearer exception messages for the user.

Hopefully #105 is perceived to improve upon this, supporting multiple error messages per compile run through basic recovery mechanisms, and recording line and column ranges for all nodes in the AST and reporting these accordingly.
