### ISSUE TITLE
#pragma-like construction for implementation-specific instructions

### ISSUE THREAD

**Issue by quantumkoen** [QE-Lab/libqasm#5]
QX simulator parses things like ```error_model depolarizing_channel, 0.001```, which is illegal in QASM 1.0 according to the definition. It would be good to extend the language with a #pragma-like construction (as seen in c/c++), that can be used to define syntactically valid implementation-specific instructions. If an implementation does not support the particular pragma, it can safely ignore it.

**Comment by kel85uk** [comment]
See #3 and #4
