### ISSUE TITLE
clearing state across multiple runs

### ISSUE THREAD

**Issue by imranashraf** [QE-Lab/libqasm#94]
compiler::SubCircuits subcircuits_object holds the state which is declared globally in grammar.y. This results in the stateful behavior which causes problem when library is used to load cqasm file multiple times.

**Comment by alxhotel** [comment]
Yep. I also had this issue in the past. I see that you have already made a fix for it in #95.

What I ended up doing is an implementation for a reentrant scanner, as suggested by @kel85uk and @quantumkoen. And it seems to work.

If that is of any use to the repository, I would like to make a PR. But the implementation depends on #91. So #91 would have to be merged before.

**Comment by imranashraf** [comment]
@alxhotel #91 seems to be interesting. currently checking it out. will merge is today in the afternoon.

**Comment by jvanstraten** [comment]
I'm closing this, as I don't think it's a problem anymore since #105.
